### PR TITLE
Resolve issue #214 to incorporate modal component keyboard tab trap

### LINKED ISSUE #214: Modal component needs to trap keyboard focus when open
The [Modal component](https://sparkpost.github.io/matchbox/?selectedKind=Overlays%7CModal&selectedStory=Toggle%20Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) needs to trap focus when open.

## Requirements

* When a modal is open, focus should be moved to the modal element itself programmatically - this can be achieved usually by using a `ref` (example [here](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element)) and adding `tabIndex="-1"`
* As the user tabs through focusable elements within the modal instance, the user should be unable to 'leave' the modal via keyboard tabbing
* This also applies to `shift+tab` when the user is on the first focusable element within a modal instance. In this situation, focus should move to the last focusable element within a modal instance.

## Resources

* The [Dialog Component in Reach UI](https://ui.reach.tech/dialog)
* Potential easy fix by leveraging [React Focus Lock](https://www.npmjs.com/package/react-focus-lock)

### PR DESCRIPTION
**Pull request by nicklemmon**
Resolves #214 

## What Changed
- Incorporated [React Focus Lock NPM package](https://www.npmjs.com/package/react-focus-lock)
- Incorporated Cypress end to end test runner
- Incorporated Cypress tab plugin to allow testing of user interaction using `tab` and `shift + tab`
- Updated modal `<Content/>` component to receive focus on mount *and* to leverage the `<FocusLock/>` component
- Incorporated end to end testing in the CI build which included:
    - Incorporated unit test and end to end testing in to a single test command
    - Added `http-server` NPM package to run "production" build of Storybook UI in the CI server
    - Added `start-server-and-test` to allow Cypress to wait for `http-server` to launch before running end to end testing
- Updated failing snapshots where necessary

## How to Test
- Run Cypress locally to verify the tab trap occurs as expected
- Visit http://localhost:9001/?selectedKind=Overlays%7CModal&selectedStory=Toggle%20Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel and verify that when the modal opens, focus moves to the modal (using the console and `document.activeElement`). Then, use `tab` and `shift + tab` to move within the modal without moving outside of the modal
- After closing the modal, resume tabbing through the DOM as usual

### CODE REVIEW

**Comment by nicklemmon** [comment]
@jonambas Need to hold off on merging this one while I explore a potential defect I encountered - while typing inside of an input, the modal was moving focus to the content on each key press. Do you know of any other modals in the app that have `<TextField/>` inside of them?

**Comment by jonambas** [comment]
> @jonambas Need to hold off on merging this one while I explore a potential defect I encountered - while typing inside of an input, the modal was moving focus to the content on each key press. Do you know of any other modals in the app that have `<TextField/>` inside of them?

@nicklemmon 
Off the top of my head:
- Get Help modal
- Import snippets modal, in the old version of templates
- Single-sign-on provision modal

**Comment by nicklemmon** [comment]
@jonambas - OK, I double checked and actually the feedback you offered earlier caught the issue that I was encountering. This should be ready to merge in, though if you want to do another beta publish and we can do some manual testing to be doubly sure I would totally get that.

**Comment by nicklemmon** [comment]
> 👍 This looks good, have the latest published under `@sparkpost/matchbox@beta`

OK, I tested all of the modals you mentioned above and the problem isn't there. Things look good to me! Should be good to go.

**Pull request merged**
